branches:
  only:
  - master
language: python
python:
- 2.7
script:
    - ../buildbot/build.sh scipy-conference/scipy_proceedings_2012
notifications:
  email:
    on_success: always
    on_failure: always
before_install:
  - git clone --recursive https://github.com/scipy-conference/openproceedings-buildbot-scipy.git -b 2012 ../buildbot
  - source ../buildbot/prepare.sh
after_success: bash ../buildbot/deploy.sh proceedings/2012
env:
  global:
    - secure: Jy78aHSAzQeVNKCnhwGLOwGTTgZ6P/RzZC8fgzYwHhpD4gPGltd177V5RYtamARbl2a5fxJE5Ls5/SOA2fI/yfbr4wqEUzuq9oGAbAia59fjL09/fGPiJb44pj89BOwi6CpPE/AFMfbX4oULlZ8gf9pyDpQ2UYZp+Nk/zSOp64Y=
